Explicitly depend on gio-unix-2.0
This fixes the following build failure on NixOS:

xfsm-client.c:32:10: fatal error: gio/gdesktopappinfo.h: No such file or directory
   32 | #include <gio/gdesktopappinfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~

This works on many distros because their `pkg-config --cflags` returns Cflags
from `Requires.private`, so this is added via gtk+-3.0. On NixOS however, we have
decided to interpret the pkg-config specification to not include Requires.private in
--cflags to avoid https://gitlab.freedesktop.org/pkg-config/pkg-config/-/issues/7
and https://gitlab.freedesktop.org/pkg-config/pkg-config/-/issues/28.

But no matter how, it is always a good idea to directly depend on all libraries whose
headers we include. Transitive dependencies may be in theory removed any time so
relying on them might be unsafe.

(cherry picked from commit a8ed1746fb4aeae6436b4c7b3a58d2926b7c4323)